/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package aplikasidatasiswa.gui;

import aplikasidatasiswa.controller.Koneksi;
import aplikasidatasiswa.dao.SiswaDao;
import aplikasidatasiswa.dao.TableDao;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import java.sql.Date;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;

/**
 *
 * @author User
 */
public class FormInputDataSiswa extends javax.swing.JFrame {

    /**
     * Creates new form FormInputDataSiswa
     */
    private String nisn, nama, tempat, jeniskelamin, agama, status, anakke, alamat, kontak, ayah, ibu, alamatorangtua,
            kontakorangtua, pekerjaanayah, pekerjaanibu, namawali, alamatwali, kontakwali, pekerjaanwali;
    SiswaDao sis = new SiswaDao();
    TableDao tbl = new TableDao();
    private String[][] rss;

    String[] namaKolom = {"Nisn", "Nama", "Jenis Kelamin", "Alamat"};
    int jmlKolom = namaKolom.length;
    int[] lebar = {300, 500, 400, 1000};

    public FormInputDataSiswa() {
        initComponents();
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        int x = (dim.width - getWidth()) / 2;
        int y = (dim.height - getHeight()) / 2;
        setLocation(x, y);
    }

    private void ShowData() {
        java.sql.Connection conn = new Koneksi().connect();
        try {
            java.sql.Statement stmt = conn.createStatement();
            java.sql.ResultSet res = stmt.executeQuery("select *from tb_siswa where nisn = '" + txtNisn.getText().trim() + "'");
            while (res.next()) {
                txtNamaSiswa.setText(res.getString("nama"));
                txtTempat.setText(res.getString("tempat"));
                jDateChooser1.setDate(res.getDate("tanggal"));
                txtAgama.setText(res.getString("agama"));
                txtAnakKe.setText(res.getString("anakke"));
                txtAlamat.setText(res.getString("alamat"));
                txtKontakSiswa.setText(res.getString("kontak"));
                txtNamaAyah.setText(res.getString("ayah"));
                txtNamaIbu.setText(res.getString("ibu"));
                txtAlamatOrangtua.setText(res.getString("alamatorangtua"));
                txtKontakOrgtua.setText(res.getString("kontakorangtua"));
                txtPekerjaanAyah.setText(res.getString("pekerjaanayah"));
                txtPekerjaanIbu.setText(res.getString("pekerjaanibu"));
                txtNamaWali.setText(res.getString("namawali"));
                txtAlamatWali.setText(res.getString("alamatwali"));
                txtKontakWali.setText(res.getString("kontakwali"));
                txtPekerjaanWali.setText(res.getString("pekerjaanwali"));               
            }
        } catch (SQLException ex) {

        }
    }

    private void Refresh() {
        txtNisn.requestFocus();
        txtNisn.setText("");
        txtNamaSiswa.setText("");
        txtTempat.setText("");
        jDateChooser1.setDate(null);
        cbJenisKelamin.setSelectedIndex(0);
        txtAgama.setText("ISLAM");
        cbStatus.setSelectedIndex(0);
        txtAnakKe.setText("");
        txtAlamat.setText("");
        txtKontakSiswa.setText("");
        txtNamaAyah.setText("");
        txtNamaIbu.setText("");
        txtAlamatOrangtua.setText("");
        txtKontakOrgtua.setText("");
        txtPekerjaanAyah.setText("");
        txtPekerjaanIbu.setText("");
        txtNamaWali.setText("");
        txtAlamatWali.setText("");
        txtKontakWali.setText("");
        txtPekerjaanWali.setText("");
        btnSave.setEnabled(true);
        btnUpdate.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtNisn = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtAlamat = new javax.swing.JTextArea();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtAlamatOrangtua = new javax.swing.JTextArea();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        txtAlamatWali = new javax.swing.JTextArea();
        txtNamaSiswa = new javax.swing.JTextField();
        txtTempat = new javax.swing.JTextField();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        cbJenisKelamin = new javax.swing.JComboBox();
        txtAgama = new javax.swing.JTextField();
        cbStatus = new javax.swing.JComboBox();
        txtAnakKe = new javax.swing.JTextField();
        txtKontakSiswa = new javax.swing.JTextField();
        txtNamaAyah = new javax.swing.JTextField();
        txtNamaIbu = new javax.swing.JTextField();
        txtKontakOrgtua = new javax.swing.JTextField();
        txtPekerjaanAyah = new javax.swing.JTextField();
        txtPekerjaanIbu = new javax.swing.JTextField();
        txtNamaWali = new javax.swing.JTextField();
        txtKontakWali = new javax.swing.JTextField();
        txtPekerjaanWali = new javax.swing.JTextField();
        btnNew = new javax.swing.JButton();
        btnSave = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        jLabel21 = new javax.swing.JLabel();
        txtSearch = new javax.swing.JTextField();
        jScrollPane6 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(0, 204, 153));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("FORM INPUT DATA SISWA");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("NISN");

        txtNisn.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtNisn.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNisnKeyTyped(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("NAMA");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("TEMPAT, TANGGAL LAHIR");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setText("JENIS KELAMIN");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setText("AGAMA");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setText("STATUS");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setText("ANAK KE");

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel9.setText("ALAMAT");

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel10.setText("KONTAK");

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel11.setText("NAMA AYAH");

        txtAlamat.setColumns(20);
        txtAlamat.setRows(5);
        txtAlamat.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtAlamatKeyTyped(evt);
            }
        });
        jScrollPane2.setViewportView(txtAlamat);

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel12.setText("NAMA IBU");

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel13.setText("ALAMAT ORANGTUA");

        txtAlamatOrangtua.setColumns(20);
        txtAlamatOrangtua.setRows(5);
        txtAlamatOrangtua.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtAlamatOrangtuaKeyTyped(evt);
            }
        });
        jScrollPane3.setViewportView(txtAlamatOrangtua);

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel14.setText("KONTAK ORANGTUA");

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel15.setText("PEKERJAAN AYAH");

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel16.setText("PEKERJAAN IBU");

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel17.setText("NAMA WALI");

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel18.setText("ALAMAT WALI");

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel19.setText("KONTAK WALI");

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel20.setText("PEKERJAAN WALI");

        txtAlamatWali.setColumns(20);
        txtAlamatWali.setRows(5);
        txtAlamatWali.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtAlamatWaliKeyTyped(evt);
            }
        });
        jScrollPane4.setViewportView(txtAlamatWali);

        txtNamaSiswa.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtNamaSiswa.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNamaSiswaKeyTyped(evt);
            }
        });

        txtTempat.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtTempat.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtTempatKeyTyped(evt);
            }
        });

        jDateChooser1.setDateFormatString("yyyy-MM-dd");

        cbJenisKelamin.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        cbJenisKelamin.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "PILIH", "LAKI-LAKI", "PEREMPUAN" }));

        txtAgama.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtAgama.setText("ISLAM");

        cbStatus.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        cbStatus.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "PILIH", "ANAK KANDUNG", "ANAK TIRI" }));

        txtAnakKe.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtAnakKe.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtAnakKeKeyTyped(evt);
            }
        });

        txtKontakSiswa.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtKontakSiswa.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtKontakSiswaKeyTyped(evt);
            }
        });

        txtNamaAyah.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtNamaAyah.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNamaAyahKeyTyped(evt);
            }
        });

        txtNamaIbu.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtNamaIbu.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNamaIbuKeyTyped(evt);
            }
        });

        txtKontakOrgtua.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtKontakOrgtua.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtKontakOrgtuaKeyTyped(evt);
            }
        });

        txtPekerjaanAyah.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtPekerjaanAyah.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtPekerjaanAyahKeyTyped(evt);
            }
        });

        txtPekerjaanIbu.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtPekerjaanIbu.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtPekerjaanIbuKeyTyped(evt);
            }
        });

        txtNamaWali.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtNamaWali.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNamaWaliKeyTyped(evt);
            }
        });

        txtKontakWali.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtKontakWali.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtKontakWaliKeyTyped(evt);
            }
        });

        txtPekerjaanWali.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtPekerjaanWali.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtPekerjaanWaliKeyTyped(evt);
            }
        });

        btnNew.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnNew.setText("REFRESH");
        btnNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewActionPerformed(evt);
            }
        });

        btnSave.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnSave.setText("SAVE");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        btnUpdate.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnUpdate.setText("UPDATE");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addGap(131, 131, 131)
                                .addComponent(txtNamaAyah))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addGap(157, 157, 157)
                                .addComponent(txtKontakSiswa))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtNamaSiswa, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtNisn, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel13)
                                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel19))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jScrollPane3)
                                    .addComponent(jScrollPane2)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                        .addComponent(txtTempat, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(cbJenisKelamin, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtAgama)
                                    .addComponent(cbStatus, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtAnakKe)
                                    .addComponent(txtNamaIbu)
                                    .addComponent(txtNamaWali)
                                    .addComponent(txtKontakWali)
                                    .addComponent(txtKontakOrgtua, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txtPekerjaanAyah, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txtPekerjaanIbu)))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(83, 83, 83)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtPekerjaanWali)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                        .addComponent(btnNew, javax.swing.GroupLayout.DEFAULT_SIZE, 89, Short.MAX_VALUE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(btnUpdate)))))
                        .addGap(27, 27, 27))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtNisn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtNamaSiswa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel4)
                        .addComponent(txtTempat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(cbJenisKelamin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtAgama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(cbStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtAnakKe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(txtKontakSiswa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(txtNamaAyah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(txtNamaIbu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtKontakOrgtua, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPekerjaanAyah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPekerjaanIbu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNamaWali, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel18))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtKontakWali, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel19))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPekerjaanWali, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel20))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNew)
                    .addComponent(btnSave)
                    .addComponent(btnUpdate))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jScrollPane1.setViewportView(jPanel3);

        jLabel21.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel21.setText("SEARCH");

        txtSearch.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtSearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtSearchKeyReleased(evt);
            }
        });

        jScrollPane6.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_ALWAYS);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jTable1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTable1KeyPressed(evt);
            }
        });
        jScrollPane6.setViewportView(jTable1);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 296, Short.MAX_VALUE)
                        .addComponent(jLabel21)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane6))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel21)
                            .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(11, 11, 11)
                        .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 427, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
        nisn = txtNisn.getText().trim();
        nama = txtNamaSiswa.getText().trim();
        tempat = txtTempat.getText().trim();
        jeniskelamin = cbJenisKelamin.getSelectedItem().toString().trim();
        agama = txtAgama.getText().trim();
        status = cbStatus.getSelectedItem().toString().trim();
        anakke = txtAnakKe.getText().trim();
        alamat = txtAlamat.getText().trim();
        kontak = txtKontakSiswa.getText().trim();
//        ayah = txtNamaAyah.getText().trim();
//        ibu = txtNamaIbu.getText().trim();
//        alamatorangtua = txtAlamatOrangtua.getText().trim();
//        kontakorangtua = txtKontakOrgtua.getText().trim();
//        pekerjaanayah = txtPekerjaanAyah.getText().trim();
//        pekerjaanibu = txtPekerjaanIbu.getText().trim();
//        namawali = txtNamaWali.getText().trim(); 
//        alamatwali = txtAlamatWali.getText().trim();
//        kontakwali = txtKontakWali.getText().trim(); 
//        pekerjaanwali = txtPekerjaanWali.getText().trim();

        if (nisn.equals("")) {
            JOptionPane.showMessageDialog(null, "Nisn Tidak Boleh Kosong !!!");
            txtNisn.requestFocus();
        } else if (nama.equals("")) {
            JOptionPane.showMessageDialog(null, "Nama Tidak Boleh Kosong !!!");
            txtNamaSiswa.requestFocus();
        } else if (tempat.equals("")) {
            JOptionPane.showMessageDialog(null, "Tempat Tidak Boleh Kosong !!!");
            txtTempat.requestFocus();
        } else if (jDateChooser1.getDate() == null) {
            JOptionPane.showMessageDialog(null, "Tanggal Harap di Isi !!!");
            jDateChooser1.requestFocus();
        } else if (jeniskelamin.equals("")) {
            JOptionPane.showMessageDialog(null, "Silahkan Pilih Jenis Kelamin !!!");
            cbJenisKelamin.requestFocus();
        } else if (agama.equals("")) {
            JOptionPane.showMessageDialog(null, "Agama Tidak Boleh Kosong !!!");
            txtAgama.requestFocus();
        } else if (status.equals("")) {
            JOptionPane.showMessageDialog(null, "Silahkan Pilih Status !!!");
            txtNisn.requestFocus();
        } else if (anakke.equals("")) {
            JOptionPane.showMessageDialog(null, "Silahkan Isi Field Anak Ke !!!");
            txtAnakKe.requestFocus();
        } else if (alamat.equals("")) {
            JOptionPane.showMessageDialog(null, "Alamat Tidak Boleh Kosong !!!");
            txtAlamat.requestFocus();
        } else if (kontak.equals("")) {
            JOptionPane.showMessageDialog(null, "Kontak Tidak Boleh Kosong !!!");
            txtKontakSiswa.requestFocus();
        } else {
            SimpleDateFormat spf = new SimpleDateFormat("yyyy-MM-dd");
            Date tanggal = Date.valueOf(spf.format(jDateChooser1.getDate()));

            java.sql.Connection conn = new Koneksi().connect();
            try {
                java.sql.PreparedStatement stmt = conn.prepareStatement("insert into tb_siswa (nisn, nama, tempat, tanggal, jeniskelamin, agama, status, anakke, alamat, kontak, ayah, ibu, alamatorangtua, kontakorangtua, pekerjaanayah, pekerjaanibu, namawali, alamatwali, kontakwali, pekerjaanwali) values (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)");
                try {
                    stmt.setString(1, nisn);
                    stmt.setString(2, nama);
                    stmt.setString(3, tempat);
                    stmt.setDate(4, tanggal);
                    stmt.setString(5, jeniskelamin);
                    stmt.setString(6, agama);
                    stmt.setString(7, status);
                    stmt.setString(8, anakke);
                    stmt.setString(9, alamat);
                    stmt.setString(10, kontak);
                    stmt.setString(11, txtNamaAyah.getText().trim());
                    stmt.setString(12, txtNamaIbu.getText().trim());
                    stmt.setString(13, txtAlamatOrangtua.getText().trim());
                    stmt.setString(14, txtKontakOrgtua.getText().trim());
                    stmt.setString(15, txtPekerjaanAyah.getText().trim());
                    stmt.setString(16, txtPekerjaanIbu.getText().trim());
                    stmt.setString(17, txtNamaWali.getText().trim());
                    stmt.setString(18, txtAlamatWali.getText().trim());
                    stmt.setString(19, txtKontakWali.getText().trim());
                    stmt.setString(20, pekerjaanwali);
                    stmt.executeUpdate();
                    JOptionPane.showMessageDialog(null, "Data Berhasil di Simpan");
                    Refresh();

                } catch (SQLException ex) {
                    JOptionPane.showMessageDialog(null, "Data Gagal Di Simpan", "Pesan", JOptionPane.INFORMATION_MESSAGE);
                }
            } catch (Exception e) {

            }
        }
    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewActionPerformed
        // TODO add your handling code here:
        Refresh();
    }//GEN-LAST:event_btnNewActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
        nisn = txtNisn.getText().trim();
        nama = txtNamaSiswa.getText().trim();
        tempat = txtTempat.getText().trim();
        jeniskelamin = cbJenisKelamin.getSelectedItem().toString().trim();
        agama = txtAgama.getText().trim();
        status = cbStatus.getSelectedItem().toString().trim();
        anakke = txtAnakKe.getText().trim();
        alamat = txtAlamat.getText().trim();
        kontak = txtKontakSiswa.getText().trim();

        if (nisn.equals("")) {
            JOptionPane.showMessageDialog(null, "Nisn Tidak Boleh Kosong !!!");
            txtNisn.requestFocus();
        } else if (nama.equals("")) {
            JOptionPane.showMessageDialog(null, "Nama Tidak Boleh Kosong !!!");
            txtNamaSiswa.requestFocus();
        } else if (tempat.equals("")) {
            JOptionPane.showMessageDialog(null, "Tempat Tidak Boleh Kosong !!!");
            txtTempat.requestFocus();
        } else if (jDateChooser1.getDate() == null) {
            JOptionPane.showMessageDialog(null, "Tanggal Harap di Isi !!!");
            jDateChooser1.requestFocus();
        } else if (jeniskelamin.equals("")) {
            JOptionPane.showMessageDialog(null, "Silahkan Pilih Jenis Kelamin !!!");
            cbJenisKelamin.requestFocus();
        } else if (agama.equals("")) {
            JOptionPane.showMessageDialog(null, "Agama Tidak Boleh Kosong !!!");
            txtAgama.requestFocus();
        } else if (status.equals("")) {
            JOptionPane.showMessageDialog(null, "Silahkan Pilih Status !!!");
            txtNisn.requestFocus();
        } else if (anakke.equals("")) {
            JOptionPane.showMessageDialog(null, "Silahkan Isi Field Anak Ke !!!");
            txtAnakKe.requestFocus();
        } else if (alamat.equals("")) {
            JOptionPane.showMessageDialog(null, "Alamat Tidak Boleh Kosong !!!");
            txtAlamat.requestFocus();
        } else if (kontak.equals("")) {
            JOptionPane.showMessageDialog(null, "Kontak Tidak Boleh Kosong !!!");
            txtKontakSiswa.requestFocus();
        } else {
            SimpleDateFormat spf = new SimpleDateFormat("yyyy-MM-dd");
            Date tanggal = Date.valueOf(spf.format(jDateChooser1.getDate()));

            java.sql.Connection conn = new Koneksi().connect();
            try {
                java.sql.PreparedStatement stmt = conn.prepareStatement("update tb_siswa set nama=?, tempat=?, tanggal=?, jeniskelamin=?, agama =?, status =?, anakke =?, alamat =?, kontak =?, ayah =?, ibu =?, alamatorangtua =?, kontakorangtua =?, pekerjaanayah =?, pekerjaanibu =?, namawali =?, alamatwali =?, kontakwali =?, pekerjaanwali =? where nisn =? ");
                try {
                    stmt.setString(1, nama);
                    stmt.setString(2, tempat);
                    stmt.setDate(3, tanggal);
                    stmt.setString(4, jeniskelamin);
                    stmt.setString(5, agama);
                    stmt.setString(6, status);
                    stmt.setString(7, anakke);
                    stmt.setString(8, alamat);
                    stmt.setString(9, kontak);
                    stmt.setString(10, txtNamaAyah.getText().trim());
                    stmt.setString(11, txtNamaIbu.getText().trim());
                    stmt.setString(12, txtAlamatOrangtua.getText().trim());
                    stmt.setString(13, txtKontakOrgtua.getText().trim());
                    stmt.setString(14, txtPekerjaanAyah.getText().trim());
                    stmt.setString(15, txtPekerjaanIbu.getText().trim());
                    stmt.setString(16, txtNamaWali.getText().trim());
                    stmt.setString(17, txtAlamatWali.getText().trim());
                    stmt.setString(18, txtKontakWali.getText().trim());
                    stmt.setString(19, pekerjaanwali);
                    stmt.setString(20, nisn);
                    stmt.executeUpdate();
                    JOptionPane.showMessageDialog(null, "Data Berhasil di Update");
                    Refresh();

                } catch (SQLException ex) {
                    JOptionPane.showMessageDialog(null, "Data Gagal Di Update", "Pesan", JOptionPane.INFORMATION_MESSAGE);
                }
            } catch (Exception e) {

            }
        }
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        int row = jTable1.getSelectedRow();
        txtNisn.setText(jTable1.getValueAt(row, 0).toString());
        ShowData();
        txtNisn.requestFocus();
        btnSave.setEnabled(false);
        btnUpdate.setEnabled(true);
    }//GEN-LAST:event_jTable1MouseClicked

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // TODO add your handling code here:
        rss = sis.ShowData();
        tbl.SetTabel(jTable1, rss, namaKolom, jmlKolom, lebar);
    }//GEN-LAST:event_formWindowActivated

    private void txtSearchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSearchKeyReleased
        // TODO add your handling code here:
        String search = txtSearch.getText();
        rss = sis.SearchData(search);
        tbl.SetTabel(jTable1, rss, namaKolom, jmlKolom, lebar);
    }//GEN-LAST:event_txtSearchKeyReleased

    private void jTable1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTable1KeyPressed
        // TODO add your handling code here:
        if (evt.getKeyChar() == KeyEvent.VK_DELETE) {
            int ok = JOptionPane.showConfirmDialog(null, "Apakah Anda Yakin Ingin Menghapus ?", "Konnfirmasi", JOptionPane.YES_NO_OPTION);
            if (ok == 0) {
                sis.Delete(txtNisn.getText().trim());
                rss = sis.ShowData();
                tbl.SetTabel(jTable1, rss, namaKolom, jmlKolom, lebar);
                Refresh();
            } else {

            }
        }
    }//GEN-LAST:event_jTable1KeyPressed

    private void txtNisnKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNisnKeyTyped
        // TODO add your handling code here:
        char karakter = evt.getKeyChar();

        if (((!(karakter >= '0') && (karakter <= '9') || (karakter == KeyEvent.VK_BACK_SPACE) || (karakter == KeyEvent.VK_DELETE) || (karakter == KeyEvent.VK_ENTER)))) {
            getToolkit().beep();
            evt.consume();
        }
        
        if(txtNisn.getText().length()== 0 && karakter == KeyEvent.VK_SPACE){
            getToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_txtNisnKeyTyped

    private void txtNamaSiswaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNamaSiswaKeyTyped
        // TODO add your handling code here:
        char karakter = evt.getKeyChar();

        if ((((karakter >= '0') && (karakter <= '9') || (karakter == KeyEvent.VK_BACK_SPACE) || (karakter == KeyEvent.VK_DELETE) || (karakter == KeyEvent.VK_ENTER)))) {
            getToolkit().beep();
            evt.consume();
        }
        
        if(txtNamaSiswa.getText().length()== 0 && karakter == KeyEvent.VK_SPACE){
            getToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_txtNamaSiswaKeyTyped

    private void txtTempatKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTempatKeyTyped
        // TODO add your handling code here:
        char karakter = evt.getKeyChar();

        if ((((karakter >= '0') && (karakter <= '9') || (karakter == KeyEvent.VK_BACK_SPACE) || (karakter == KeyEvent.VK_DELETE) || (karakter == KeyEvent.VK_ENTER)))) {
            getToolkit().beep();
            evt.consume();
        }
        
        if(txtTempat.getText().length()== 0 && karakter == KeyEvent.VK_SPACE){
            getToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_txtTempatKeyTyped

    private void txtAnakKeKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtAnakKeKeyTyped
        // TODO add your handling code here:
        char karakter = evt.getKeyChar();

        if(txtAnakKe.getText().length()== 0 && karakter == KeyEvent.VK_SPACE){
            getToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_txtAnakKeKeyTyped

    private void txtAlamatKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtAlamatKeyTyped
        // TODO add your handling code here:
        char karakter = evt.getKeyChar();

        if(txtAlamat.getText().length()== 0 && karakter == KeyEvent.VK_SPACE){
            getToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_txtAlamatKeyTyped

    private void txtKontakSiswaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtKontakSiswaKeyTyped
        // TODO add your handling code here:
        char karakter = evt.getKeyChar();

        if (!(((karakter >= '0') && (karakter <= '9') || (karakter == KeyEvent.VK_BACK_SPACE) || (karakter == KeyEvent.VK_DELETE) || (karakter == KeyEvent.VK_ENTER)))) {
            getToolkit().beep();
            evt.consume();
        }
        
        if(txtKontakSiswa.getText().length()== 0 && karakter == KeyEvent.VK_SPACE){
            getToolkit().beep();
            evt.consume();
        }
        
        if(txtKontakSiswa.getText().length() >= 12){
            getToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_txtKontakSiswaKeyTyped

    private void txtNamaAyahKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNamaAyahKeyTyped
        // TODO add your handling code here:
        char karakter = evt.getKeyChar();

        if ((((karakter >= '0') && (karakter <= '9') || (karakter == KeyEvent.VK_BACK_SPACE) || (karakter == KeyEvent.VK_DELETE) || (karakter == KeyEvent.VK_ENTER)))) {
            getToolkit().beep();
            evt.consume();
        }
        
        if(txtNamaAyah.getText().length()== 0 && karakter == KeyEvent.VK_SPACE){
            getToolkit().beep();
            evt.consume();
        }
        
    }//GEN-LAST:event_txtNamaAyahKeyTyped

    private void txtNamaIbuKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNamaIbuKeyTyped
        // TODO add your handling code here:
        char karakter = evt.getKeyChar();

        if ((((karakter >= '0') && (karakter <= '9') || (karakter == KeyEvent.VK_BACK_SPACE) || (karakter == KeyEvent.VK_DELETE) || (karakter == KeyEvent.VK_ENTER)))) {
            getToolkit().beep();
            evt.consume();
        }
        
        if(txtNamaIbu.getText().length()== 0 && karakter == KeyEvent.VK_SPACE){
            getToolkit().beep();
            evt.consume();
        }
        
    }//GEN-LAST:event_txtNamaIbuKeyTyped

    private void txtAlamatOrangtuaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtAlamatOrangtuaKeyTyped
        // TODO add your handling code here:        
        char karakter = evt.getKeyChar();

        if(txtAlamatOrangtua.getText().length()== 0 && karakter == KeyEvent.VK_SPACE){
            getToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_txtAlamatOrangtuaKeyTyped

    private void txtKontakOrgtuaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtKontakOrgtuaKeyTyped
        // TODO add your handling code here:
        char karakter = evt.getKeyChar();

        if (!(((karakter >= '0') && (karakter <= '9') || (karakter == KeyEvent.VK_BACK_SPACE) || (karakter == KeyEvent.VK_DELETE) || (karakter == KeyEvent.VK_ENTER)))) {
            getToolkit().beep();
            evt.consume();
        }
        
        if(txtKontakOrgtua.getText().length()== 0 && karakter == KeyEvent.VK_SPACE){
            getToolkit().beep();
            evt.consume();
        }
        
        if(txtKontakOrgtua.getText().length() >= 12){
            getToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_txtKontakOrgtuaKeyTyped

    private void txtKontakWaliKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtKontakWaliKeyTyped
        // TODO add your handling code here:
        char karakter = evt.getKeyChar();

        if (!(((karakter >= '0') && (karakter <= '9') || (karakter == KeyEvent.VK_BACK_SPACE) || (karakter == KeyEvent.VK_DELETE) || (karakter == KeyEvent.VK_ENTER)))) {
            getToolkit().beep();
            evt.consume();
        }
        
        if(txtKontakWali.getText().length()== 0 && karakter == KeyEvent.VK_SPACE){
            getToolkit().beep();
            evt.consume();
        }
        
        if(txtKontakWali.getText().length() >= 12){
            getToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_txtKontakWaliKeyTyped

    private void txtPekerjaanAyahKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPekerjaanAyahKeyTyped
        // TODO add your handling code here:
        char karakter = evt.getKeyChar();

        if ((((karakter >= '0') && (karakter <= '9') || (karakter == KeyEvent.VK_BACK_SPACE) || (karakter == KeyEvent.VK_DELETE) || (karakter == KeyEvent.VK_ENTER)))) {
            getToolkit().beep();
            evt.consume();
        }
        
        if(txtPekerjaanAyah.getText().length()== 0 && karakter == KeyEvent.VK_SPACE){
            getToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_txtPekerjaanAyahKeyTyped

    private void txtPekerjaanIbuKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPekerjaanIbuKeyTyped
        // TODO add your handling code here:
        char karakter = evt.getKeyChar();

        if ((((karakter >= '0') && (karakter <= '9') || (karakter == KeyEvent.VK_BACK_SPACE) || (karakter == KeyEvent.VK_DELETE) || (karakter == KeyEvent.VK_ENTER)))) {
            getToolkit().beep();
            evt.consume();
        }
        
        if(txtPekerjaanIbu.getText().length()== 0 && karakter == KeyEvent.VK_SPACE){
            getToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_txtPekerjaanIbuKeyTyped

    private void txtNamaWaliKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNamaWaliKeyTyped
        // TODO add your handling code here:
        char karakter = evt.getKeyChar();

        if ((((karakter >= '0') && (karakter <= '9') || (karakter == KeyEvent.VK_BACK_SPACE) || (karakter == KeyEvent.VK_DELETE) || (karakter == KeyEvent.VK_ENTER)))) {
            getToolkit().beep();
            evt.consume();
        }
        
        if(txtNamaWali.getText().length()== 0 && karakter == KeyEvent.VK_SPACE){
            getToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_txtNamaWaliKeyTyped

    private void txtAlamatWaliKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtAlamatWaliKeyTyped
        // TODO add your handling code here:
        char karakter = evt.getKeyChar();

        if(txtAlamatWali.getText().length()== 0 && karakter == KeyEvent.VK_SPACE){
            getToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_txtAlamatWaliKeyTyped

    private void txtPekerjaanWaliKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPekerjaanWaliKeyTyped
        // TODO add your handling code here:
        char karakter = evt.getKeyChar();

        if ((((karakter >= '0') && (karakter <= '9') || (karakter == KeyEvent.VK_BACK_SPACE) || (karakter == KeyEvent.VK_DELETE) || (karakter == KeyEvent.VK_ENTER)))) {
            getToolkit().beep();
            evt.consume();
        }
        
        if(txtPekerjaanWali.getText().length()== 0 && karakter == KeyEvent.VK_SPACE){
            getToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_txtPekerjaanWaliKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormInputDataSiswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormInputDataSiswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormInputDataSiswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormInputDataSiswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormInputDataSiswa().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnNew;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JComboBox cbJenisKelamin;
    private javax.swing.JComboBox cbStatus;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField txtAgama;
    private javax.swing.JTextArea txtAlamat;
    private javax.swing.JTextArea txtAlamatOrangtua;
    private javax.swing.JTextArea txtAlamatWali;
    private javax.swing.JTextField txtAnakKe;
    private javax.swing.JTextField txtKontakOrgtua;
    private javax.swing.JTextField txtKontakSiswa;
    private javax.swing.JTextField txtKontakWali;
    private javax.swing.JTextField txtNamaAyah;
    private javax.swing.JTextField txtNamaIbu;
    private javax.swing.JTextField txtNamaSiswa;
    private javax.swing.JTextField txtNamaWali;
    private javax.swing.JTextField txtNisn;
    private javax.swing.JTextField txtPekerjaanAyah;
    private javax.swing.JTextField txtPekerjaanIbu;
    private javax.swing.JTextField txtPekerjaanWali;
    private javax.swing.JTextField txtSearch;
    private javax.swing.JTextField txtTempat;
    // End of variables declaration//GEN-END:variables
}
